name: Deploy to WP Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: mrpobackend
          SRC_PATH: "./wp-content-files"
          REMOTE_PATH: "./wp-content-files"

          # Updated FLAGS path references:
          FLAGS: "-azvr --inplace --delete --include-from wp-content-files/rsync-config/includes.txt --exclude=.* --exclude-from wp-content-files/rsync-config/excludes.txt"
          SCRIPT: "wp-content/bin/post-deploy.sh"
